kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-postgres-sc
  labels:
    app: postgres
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  io_profile: "db_remote"
  priority_io: "high"
allowVolumeExpansion: true
