kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data
  namespace: postgres
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: px-postgres-sc
