apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-sa-pxbackup-testing
  namespace: px-backup-testing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: px-backup-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: px-backup-user
subjects:
- kind: ServiceAccount
  name: svc-sa-pxbackup-testing
  namespace: px-backup-testing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: px-backup-user
rules:
- apiGroups:
  - stork.libopenstorage.org
  resources:
  - "*"
  verbs:
  - get
  - list
- apiGroups:
  - "*"
  resources:
  - "namespaces"
  - "persistentvolumes"
  - "clusterroles"
  - "clusterrolebindings"
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: px-backup-user
  namespace: px-backup-testing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: px-backup-user
subjects:
- kind: ServiceAccount
  name: svc-sa-pxbackup-testing
  namespace: px-backup-testing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: px-backup-user
 namespace: px-backup-testing
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
- apiGroups:
  - stork.libopenstorage.org
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list"]