apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: postgres
  labels:
    app: postgres
  annotations:
    volume.beta.kubernetes.io/storage-class: px-sec-enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
