apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-sec-enabled
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  io_profile: "db_remote"
  openstorage.io/auth-secret-name: px-user-token
  openstorage.io/auth-secret-namespace: portworx
allowVolumeExpansion: true